### ISSUE TITLE
Error when I run the toy in google colab

### ISSUE THREAD

**Issue by yaiza612** [stasaki/DEcode#1]
Good day. When I try to run Run_DEcode_toy.ipynb in Google Colab I got the following error: 
`Using TensorFlow backend.
{u'n_feature_mRNA': 372, u'DNA_n_channel_1st': 120.0, u'Last_fullConLayer': 2.0, u'DNA_conv_strides': 1.0, u'ConvRelu': u'No', u'FullRelu': u'Yes', u'n_feature_mRNA_basic': 1, u'n_feature_promoter': 726, u'lr': 0.001, u'RNA_n_channel_1st': 160.0, u'Last_n_channel': 160.0, u'RNA_conv_strides': 2.0, u'DNA_n_ConvLayer': 4.0, u'RNA_n_ConvLayer': 1.0, u'n_out': 54, u'Add_basic_info': u'No'}

TypeErrorTraceback (most recent call last)
<ipython-input-10-67cc68dedc5c> in <module>()
     22 # train model 10 times
     23 for i in range(10):
---> 24     main(params)
     25 # Descriptions of outputs
     26 #{time_stamp}_history.json: Model performance at each epoch. Loss and val_loss indicates mean-squred error for traing data and validation data,respectively. Pcor and pcor_loss indicates Pearson's correlation for traing data and validation data,respectively.

6 frames
<ipython-input-9-d631e1b400df> in main(params)
     90     # Saving optimization history
     91     with open(outloc+time_stamp+'_history.json', 'w') as f:
---> 92         json.dump(result.history, f)
     93 
     94     # Saving model and learning paramters

/usr/lib/python2.7/json/__init__.pyc in dump(obj, fp, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, encoding, default, sort_keys, **kw)
    187     # could accelerate with writelines in some versions of Python, at
    188     # a debuggability cost
--> 189     for chunk in iterable:
    190         fp.write(chunk)
    191 

/usr/lib/python2.7/json/encoder.pyc in _iterencode(o, _current_indent_level)
    432                 yield chunk
    433         elif isinstance(o, dict):
--> 434             for chunk in _iterencode_dict(o, _current_indent_level):
    435                 yield chunk
    436         else:

/usr/lib/python2.7/json/encoder.pyc in _iterencode_dict(dct, _current_indent_level)
    406                 else:
    407                     chunks = _iterencode(value, _current_indent_level)
--> 408                 for chunk in chunks:
    409                     yield chunk
    410         if newline_indent is not None:

/usr/lib/python2.7/json/encoder.pyc in _iterencode_list(lst, _current_indent_level)
    330                 else:
    331                     chunks = _iterencode(value, _current_indent_level)
--> 332                 for chunk in chunks:
    333                     yield chunk
    334         if newline_indent is not None:

/usr/lib/python2.7/json/encoder.pyc in _iterencode(o, _current_indent_level)
    440                     raise ValueError("Circular reference detected")
    441                 markers[markerid] = o
--> 442             o = _default(o)
    443             for chunk in _iterencode(o, _current_indent_level):
    444                 yield chunk

/usr/lib/python2.7/json/encoder.pyc in default(self, o)
    182 
    183         """
--> 184         raise TypeError(repr(o) + " is not JSON serializable")
    185 
    186     def encode(self, o):

TypeError: 0.08371734 is not JSON serializable`

I'm not changing anything, I just run the code. 
Thank you for your help in advance.

**Comment by stasaki** [comment]
Thank you for bringing this to our attention. Since Google Colab has updated the installed libraries, the code doesn't work there anymore. Please consider using Code Ocean as it guarantees reproducibility.
